services:
  # Base de datos para WordPress
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_SIMPLE}
      MYSQL_DATABASE: ${MYSQL_DATABASE_SIMPLE}
      MYSQL_USER: ${MYSQL_USER_SIMPLE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_SIMPLE}
    networks:
      broker_network:
        aliases:
          - mysql

  # WordPress único en localhost
  wordpress:
    image: wordpress:6.8.1
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html
      - ./n8n-project/wordpress/broker-integration:/var/www/html/wp-content/plugins/broker-integration
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST_SIMPLE}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER_SIMPLE}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD_SIMPLE}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME_SIMPLE}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '${WP_MEMORY_LIMIT_SIMPLE}');
        define('WP_BROKER_WEBHOOK_URL', '${WP_BROKER_WEBHOOK_URL_SIMPLE}');
        define('WP_BROKER_WEBHOOK_SECRET', '${WP_BROKER_WEBHOOK_SECRET_SIMPLE}');
    ports:
      - "8888:80"
    networks:
      broker_network:
        aliases:
          - wordpress-main

  # n8n para workflows
  n8n:
    image: n8nio/n8n:1.99.1
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_HOST=${N8N_HOST_SIMPLE}
      - N8N_PORT=${N8N_PORT_SIMPLE}
      - N8N_PROTOCOL=${N8N_PROTOCOL_SIMPLE}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL_SIMPLE}
      - WEBHOOK_URL=${WEBHOOK_URL_SIMPLE}
      - WORDPRESS_URL=${WORDPRESS_URL_SIMPLE}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET_SIMPLE}
      - N8N_DIAGNOSTICS_ENABLED=${N8N_DIAGNOSTICS_ENABLED_SIMPLE}
      - N8N_USER_MANAGEMENT_DISABLED=${N8N_USER_MANAGEMENT_DISABLED_SIMPLE}
      - EXECUTIONS_PROCESS=${EXECUTIONS_PROCESS_SIMPLE}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE_SIMPLE}
      - TZ=${TZ_SIMPLE}
    networks:
      broker_network:
        aliases:
          - n8n-main

  

volumes:
  db_data:
  wp_data:
  n8n_data:

networks:
  broker_network:
    driver: bridge 