version: '3'

services:
  # Base de datos compartida para todos los sitios
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - broker_network

  # Inicialización de bases de datos adicionales
  db-init:
    image: mysql:5.7
    depends_on:
      - db
    command: >
      bash -c "
        sleep 15;
        mysql -h db -u root -p${MYSQL_ROOT_PASSWORD} -e "
        CREATE DATABASE IF NOT EXISTS broker_agents;
        CREATE DATABASE IF NOT EXISTS broker_clients;
        CREATE USER IF NOT EXISTS 'broker_user'@'%' IDENTIFIED BY 'broker_password';
        GRANT ALL PRIVILEGES ON broker_agents.* TO 'broker_user'@'%';
        GRANT ALL PRIVILEGES ON broker_clients.* TO 'broker_user'@'%';
        GRANT ALL PRIVILEGES ON broker_main.* TO 'broker_user'@'%';
        FLUSH PRIVILEGES;
        \"
      "
    networks:
      - broker_network

  # WordPress principal (krediagil.com)
  wordpress-main:
    image: wordpress:6.8.1
    depends_on:
      - db
      - db-init
    volumes:
      - wp_data_main:/var/www/html
      - ./:/var/www/html/wp-content/plugins/broker-integration
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', '${WP_HOME_MAIN}');
        define('WP_SITEURL', '${WP_SITEURL_MAIN}');
    ports:
      - "8000:80"
    networks:
      broker_network:
        aliases:
          - krediagil.com

  # WordPress para agentes (agentes.krediagil.com)
  wordpress-agents:
    image: wordpress:6.8.1
    depends_on:
      - db
      - db-init
    volumes:
      - wp_data_agents:/var/www/html
      - ./:/var/www/html/wp-content/plugins/broker-integration
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME_AGENTS}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', '${WP_HOME_AGENTS}');
        define('WP_SITEURL', '${WP_SITEURL_AGENTS}');
    ports:
      - "8001:80"
    networks:
      broker_network:
        aliases:
          - agentes.krediagil.com

  # WordPress para clientes (clientes.krediagil.com)
  wordpress-clients:
    image: wordpress:6.8.1
    depends_on:
      - db
      - db-init
    volumes:
      - wp_data_clients:/var/www/html
      - ./:/var/www/html/wp-content/plugins/broker-integration
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME_CLIENTS}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', '${WP_HOME_CLIENTS}');
        define('WP_SITEURL', '${WP_SITEURL_CLIENTS}');
    ports:
      - "8002:80"
    networks:
      broker_network:
        aliases:
          - clientes.krediagil.com

  # n8n para workflows
  n8n:
    image: n8nio/n8n:1.99.1
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-flows:/home/node/.n8n/workflows
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      # Variables para integración WordPress
      - WORDPRESS_URL=${N8N_WORDPRESS_URL}
      - WORDPRESS_USER=${N8N_WORDPRESS_USER}
      - WORDPRESS_APP_PASSWORD=${N8N_WORDPRESS_APP_PASSWORD}
      # Variables para subdirectorios
      - MAIN_SITE=${MAIN_SITE}
      - AGENTS_PATH=${AGENTS_PATH}
      - CLIENTS_PATH=${CLIENTS_PATH}
    networks:
      - broker_network

  # PostgreSQL para n8n
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - broker_network

  # phpMyAdmin para gestión de bases de datos
  

volumes:
  db_data:
  wp_data_main:
  wp_data_agents:
  wp_data_clients:
  n8n_data:
  postgres_data:

networks:
  broker_network:
    driver: bridge 