version: '3'

services:
  # Base de datos compartida para todos los sitios
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: broker_root_password
      MYSQL_DATABASE: broker_main
      MYSQL_USER: broker_user
      MYSQL_PASSWORD: broker_password
    networks:
      - broker_network

  # Inicialización de bases de datos adicionales
  db-init:
    image: mysql:5.7
    depends_on:
      - db
    command: >
      bash -c "
        sleep 15;
        mysql -h db -u root -pbroker_root_password -e \"
        CREATE DATABASE IF NOT EXISTS broker_agents;
        CREATE DATABASE IF NOT EXISTS broker_clients;
        CREATE USER IF NOT EXISTS 'broker_user'@'%' IDENTIFIED BY 'broker_password';
        GRANT ALL PRIVILEGES ON broker_agents.* TO 'broker_user'@'%';
        GRANT ALL PRIVILEGES ON broker_clients.* TO 'broker_user'@'%';
        GRANT ALL PRIVILEGES ON broker_main.* TO 'broker_user'@'%';
        FLUSH PRIVILEGES;
        \"
      "
    networks:
      - broker_network

  # WordPress principal (krediagil.com)
  wordpress-main:
    image: wordpress:latest
    depends_on:
      - db
      - db-init
    volumes:
      - wp_data_main:/var/www/html
      - ./:/var/www/html/wp-content/plugins/broker-integration
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: broker_user
      WORDPRESS_DB_PASSWORD: broker_password
      WORDPRESS_DB_NAME: broker_main
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8000');
        define('WP_SITEURL', 'http://localhost:8000');
    ports:
      - "8000:80"
    networks:
      broker_network:
        aliases:
          - krediagil.com

  # WordPress para agentes (agentes.krediagil.com)
  wordpress-agents:
    image: wordpress:latest
    depends_on:
      - db
      - db-init
    volumes:
      - wp_data_agents:/var/www/html
      - ./:/var/www/html/wp-content/plugins/broker-integration
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: broker_user
      WORDPRESS_DB_PASSWORD: broker_password
      WORDPRESS_DB_NAME: broker_agents
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8001');
        define('WP_SITEURL', 'http://localhost:8001');
    ports:
      - "8001:80"
    networks:
      broker_network:
        aliases:
          - agentes.krediagil.com

  # WordPress para clientes (clientes.krediagil.com)
  wordpress-clients:
    image: wordpress:latest
    depends_on:
      - db
      - db-init
    volumes:
      - wp_data_clients:/var/www/html
      - ./:/var/www/html/wp-content/plugins/broker-integration
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: broker_user
      WORDPRESS_DB_PASSWORD: broker_password
      WORDPRESS_DB_NAME: broker_clients
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8002');
        define('WP_SITEURL', 'http://localhost:8002');
    ports:
      - "8002:80"
    networks:
      broker_network:
        aliases:
          - clientes.krediagil.com

  # n8n para workflows
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-flows:/home/node/.n8n/workflows
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_WEBHOOK_URL=http://n8n:5678/
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - WEBHOOK_SECRET=broker_webhook_secret
      # Variables para integración WordPress
      - WORDPRESS_URL=http://wordpress-main
      - WORDPRESS_USER=admin
      - WORDPRESS_APP_PASSWORD=password
      # Variables para subdirectorios
      - MAIN_SITE=http://localhost:8000
      - AGENTS_PATH=/agentes
      - CLIENTS_PATH=/clientes
    networks:
      - broker_network

  # PostgreSQL para n8n
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - broker_network

  # phpMyAdmin para gestión de bases de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: broker_root_password
    ports:
      - "8080:80"
    networks:
      - broker_network

volumes:
  db_data:
  wp_data_main:
  wp_data_agents:
  wp_data_clients:
  n8n_data:
  postgres_data:

networks:
  broker_network:
    driver: bridge 